In [1]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
# the above code will print a 0 dim tensor
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one_d = tf.constant([2,9,9])
print(tensor_one_d)

tf.Tensor([2 9 9], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [2,3,4],
    [9,0,1]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [2 3 4]
 [9 0 1]], shape=(3, 3), dtype=int32)


In [ ]:
print(tensor_two_d.ndim)

2


In [ ]:
tensor_one_d = tf.constant([2,9,9] , dtype=tf.float16)
print(tensor_one_d)

tf.Tensor([2. 9. 9.], shape=(3,), dtype=float16)


In [ ]:
tensor_one_d = tf.constant([2,9,9] , dtype=tf.float64)
casted_tensor_one_d = tf.cast(tensor_one_d , dtype = tf.int16)
print(casted_tensor_one_d)
print(tensor_one_d)

tf.Tensor([2 9 9], shape=(3,), dtype=int16)
tf.Tensor([2. 9. 9.], shape=(3,), dtype=float64)


In [ ]:
casted_tensor_bool = tf.cast(tensor_one_d , dtype = tf.bool)
print(casted_tensor_bool)

tf.Tensor([ True  True  True], shape=(3,), dtype=bool)


In [ ]:
tensor_string =tf.constant("hello world")
print(tensor_string)


tf.Tensor(b'hello world', shape=(), dtype=string)


In [ ]:
tensor_string =tf.constant(["hello world" , "hi" ])
print(tensor_string)


tf.Tensor([b'hello world' b'hi'], shape=(2,), dtype=string)


In [ ]:
import numpy as np

In [ ]:
npArray = np.array([1,2,2])
print(npArray);

[1 2 2]


In [ ]:
converted_tensor = tf.convert_to_tensor(npArray)
print(converted_tensor)

tf.Tensor([1 2 2], shape=(3,), dtype=int64)


In [ ]:
#construct an identity matrix or a batch of matrix

eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    name = None,
    batch_shape = None,
    dtype = tf.dtypes.float32
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
#construct an identity matrix or a batch of matrix


eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = 3,
    name = None,
    batch_shape = [3,6] ,
    dtype = tf.dtypes.float32
)
print(eye_tensor)


tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]
   [0. 

In [ ]:
#fill creates a tensor with a filled scaler value
fill_tensor = tf.fill(
    [1,3,5] , 0 , name=None
)
print(fill_tensor)

tf.Tensor(
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]], shape=(1, 3, 5), dtype=int32)


In [ ]:
#creates a tensor of all ones that have the same shape as the input
ones_like_tensor = tf.ones_like(
    fill_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]], shape=(1, 3, 5), dtype=int32)


In [ ]:
print(tensor_two_d.shape)

(3, 3)


In [ ]:
# return the rank of tensor
tensor_two_rank = tf.rank(tensor_two_d)
print(tensor_two_rank)

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
#creating random value tensor
random_tensor = tf.random.normal(
    [3,2],
    mean = 1000000.0,
    stddev = 9992029202021.0,
    dtype = tf.dtypes.float32,
    seed = None,
    name = None
)
print(random_tensor)

tf.Tensor(
[[-8.9495647e+12 -2.0743484e+12]
 [ 5.5911991e+12 -1.8037969e+12]
 [-1.4125043e+13  8.6833192e+12]], shape=(3, 2), dtype=float32)


In [ ]:
#to produce reproducable tensor we need to set up globally seed value and a seed value in a uniform tensor
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,] , maxval = 3 , dtype=tf.int32 , seed=10))


tf.Tensor([2 0 1], shape=(3,), dtype=int32)


In [ ]:
#tensor indexing
tensor_indexed = tf.constant([3,2,4,5,3,2])
print(tensor_indexed)

tf.Tensor([3 2 4 5 3 2], shape=(6,), dtype=int32)


In [ ]:
#to get first four element out of the above tensor
print(tensor_indexed[0 : 4])
print(tensor_indexed[1 : 5])

tf.Tensor([3 2 4 5], shape=(4,), dtype=int32)
tf.Tensor([2 4 5 3], shape=(4,), dtype=int32)


In [ ]:
x1 = tf.constant([[5,3,6,6,4,6]] , dtype = tf.float32)
x2 = tf.constant([[7] , [5] , [3]] , dtype = tf.float32)
print(x1.shape)
print(x2.shape)
print(tf.math.multiply(x1 , x2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
#tf.math.argmax will give max of two tensor and tf.math.argmin will give minimum of two tensors
x = tf.constant([[2,29,39] , [3,11,16] , [14,45,23]])
print(tf.math.argmax(x))
y = tf.constant([1,45,32])
print(tf.math.argmax(y))

tf.Tensor([2 2 0], shape=(3,), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)


In [ ]:
z = tf.constant([0,2,1])
print(tf.math.argmax(z))

tf.Tensor(1, shape=(), dtype=int64)


In [ ]:
print(tf.math.argmax(x , 0))
print(tf.math.argmin(x))

tf.Tensor([2 2 0], shape=(3,), dtype=int64)
tf.Tensor([0 1 1], shape=(3,), dtype=int64)


In [ ]:
#equal will check whether the tensors are equal or not
print(tf.math.equal(y , z))

tf.Tensor([False False False], shape=(3,), dtype=bool)


In [ ]:
#pow
a = tf.constant(2)
b = tf.constant(3)
print(tf.pow(a , b))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
#find the mean
print(tf.math.reduce_mean(x , axis = 0 , keepdims = False , name = None))

tf.Tensor([ 6 28 26], shape=(3,), dtype=int32)


In [ ]:
#sigmoid function
tf.math.top_k(x)
#the second part gives indexes of the array
# by default it is sorted

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[39],
       [16],
       [45]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [1]], dtype=int32)>)

In [ ]:
#linear algebra
#matmul multiples mat a by b
#total columns in matrix 1 should be equal to total rows in matrix 2
x1 = tf.constant([
    [1,4,5],
    [4,5,3],
    [4,3,2]
])
x2 = tf.constant([
    [1,1,5],
    [4,5,3],
    [4,3,2]
])
tf.linalg.matmul(
    x1,
    x2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)
#sparse sometimes there are matrices which have mostly zeros, tensorflow has a way to optimize those tensors . These tensors are called sparse tensors
#

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[37, 36, 27],
       [36, 38, 41],
       [24, 25, 33]], dtype=int32)>

In [ ]:
print(x1@x2) # this is also another way to multiply matrixes

tf.Tensor(
[[37 36 27]
 [36 38 41]
 [24 25 33]], shape=(3, 3), dtype=int32)


In [ ]:
#transpose
print(tf.transpose(x1))

tf.Tensor(
[[1 4 4]
 [4 5 3]
 [5 3 2]], shape=(3, 3), dtype=int32)


In [ ]:
print(x1)

tf.Tensor(
[[1 4 5]
 [4 5 3]
 [4 3 2]], shape=(3, 3), dtype=int32)


In [ ]:
#band_part
#Copy a tensor setting everything outside a central band in each innermost matrix to zero.
#lower < 0 or m - n <= lower and upper < 0 or n - m <= upper
tensor_two_d = tf.constant([
    [1,2,-4],
    [4,5,6]
]);
#m -- rows , n --- columns

tf.linalg.band_part(tensor_two_d , 0 , 0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 5, 0]], dtype=int32)>

In [3]:
#tf.linalg.cross computes cross product
#tf.linalg.cholesky computes matrix decomposition
#tf.linalg.det computes determinant of the matrix
#tf.linalg.inv computes inverse of the matrix and the matrix should be a square matrix
#otherwise this will generate an error

tensor_two_d = tf.constant([
    [1,3],
    [4, 5]
], dtype = tf.float32)

In [ ]:
print(tf.linalg.inv(tensor_two_d))

tf.Tensor(
[[-0.71428573  0.42857143]
 [ 0.5714286  -0.14285715]], shape=(2, 2), dtype=float32)


In [4]:
#on multiplying tf.linalg.inv matrix as depicted in above cell and tensor_two_d you can get the identity matrix.
#accepted data types are float64 , flotat32.half
#tf.linalg.svd will compute svd decomposition of a tensor

print(tf.linalg.svd(tensor_two_d))

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([7.07251   , 0.98974764], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.4288783 , -0.90336215],
       [ 0.90336215,  0.4288783 ]], dtype=float32)>, <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.57155484,  0.82056385],
       [ 0.82056385, -0.57155484]], dtype=float32)>)


In [5]:
#Returns the sum of the elements of the diagonal of the input 2-D matrix.
print(tf.linalg.trace(tensor_two_d))

tf.Tensor(6.0, shape=(), dtype=float32)


In [6]:
import numpy as np

In [9]:
A = np.array([
    [1,2,3],
    [3,4,5]
])
B = np.array([
    [3,4],
    [2,4],
    [6,7]
])
print(A.shape)
print(B.shape)
print(np.matmul(A, B))

(2, 3)
(3, 2)
[[25 33]
 [47 63]]


In [15]:
#einsum multiply A with B in a particular way to create new array of products; and then maybe
#sum this new array along particular axes; and then maybe
#transpose the axes of the new array in a particular order.
print("transpose")
print(A.T)
print("einsum")
print(np.einsum("ij -> ji" , A))

transpose
[[1 3]
 [2 4]
 [3 5]]
einsum
[[1 3]
 [2 4]
 [3 5]]


In [21]:
nested_list2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [18]:
nested_list = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
               [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

In [25]:
print(nested_list2.shape , nested_list.shape)
#print(np.matmul(nested_list , nested_list2)) # do adjust the shapes of the matrixes to multiply them


(2, 3, 4) (2, 3, 4)


In [26]:
#sum up all the elements in the array
print(np.sum(nested_list))

300


In [28]:
#summing using einum operator
print(np.einsum("bij -> " , nested_list))

300


In [31]:
#suming up elements in each column
#print(np.einsum('ij -> j' , nested_list))
#if we write the axis to ij -> i then it will sum the entire row

In [ ]:
Q = batch_size , s_q , model_size
K = key_size , s_k, model_size


In [32]:
Q = np.random.randn(32,89,90) bqm
K = np.random.randn(16,89,90) bkm
np.einsum("bqm, bkm -> b" , Q , K).shape

In [37]:
#common tensorflow functions
x = tf.constant([
    1,2,3,4
])
print(tf.expand_dims(x , axis = 0).shape)

(1, 4)


In [40]:
#squeeze reduces the dimension of the tensor
#reshape can also be used to squeeze a tensor

x_squeeze = tf.squeeze(tf.expand_dims(x , axis = 0) , axis = 0)
print(x_squeeze.shape)

(4,)


In [41]:
#reshape
x = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])
tf.reshape(x , [8])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [42]:
tf.reshape(x , [4,2,1])

<tf.Tensor: shape=(4, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]], dtype=int32)>

In [45]:
#concat basically appends the matrix into each other
t1 = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])
t2 = tf.constant([
    [1,2,3,4],
    [5,6,7,8]
])
tf.stack([t1,t2] , axis = 0)

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]], dtype=int32)>

In [50]:
tensor_two_d = [
    [1,2,0],
    [2,],
    [3,2,1]
]
print(tensor_two_d)
tensor_ragged = tf.ragged.constant(tensor_two_d)
print(tensor_ragged.shape)
print(tensor_ragged)

[[1, 2, 0], [2], [3, 2, 1]]
(3, None)
<tf.RaggedTensor [[1, 2, 0], [2], [3, 2, 1]]>


In [59]:
#print(tf.RaggedTensor.from_row_lengths(
    #values = [3,1,4,1,5,9,0,2,1],
    #row_lengths=[2,1,0,3,4]
#))
#tensor_spars = tf.sparse.SparseTensor(
   # indices = [[1,1] , [3,4]] , values = [11,56] , dense_shape = [ 5,6]
#)

#print(tensor_spars)

In [52]:
tensor_string = tf.constant([
    "hello " , "i am"
])
print(tensor_string)

tf.Tensor([b'hello ' b'i am'], shape=(2,), dtype=string)


In [57]:
tf.strings.join(tensor_string , separator = "+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello +i am'>

In [ ]:
Variables

In [58]:
x_var = tf.Variable(x , name = 'var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [64]:
with tf.device('GPU:0'):
  x_var1 = tf.Variable(0.2)
print(x_var1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.2>


In [63]:
with tf.device('CPU:0'):
  x_var2 = tf.Variable(0.2)
print(x_var2)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.2>
